// ─── User Data ──────────────────────────────────────────────
export const userData = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    info: {
      status: "Active",
      role: "Admin",
      yearsOfExperience: 5,
      department: "Engineering",
      location: "New York",
    },
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    info: {
      status: "Inactive",
      role: "Manager",
      yearsOfExperience: 7,
      department: "HR",
      location: "San Francisco",
    },
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice@example.com",
    info: {
      status: "Active",
      role: "Developer",
      yearsOfExperience: 3,
      department: "Engineering",
      location: "Boston",
    },
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob@example.com",
    info: {
      status: "Pending",
      role: "Designer",
      yearsOfExperience: 2,
      department: "Design",
      location: "Chicago",
    },
  },
  {
    id: 5,
    name: "Charlie Davis",
    email: "charlie@example.com",
    info: {
      status: "Active",
      role: "Developer",
      yearsOfExperience: 4,
      department: "Engineering",
      location: "Austin",
    },
  },
  {
    id: 6,
    name: "Diana Evans",
    email: "diana@example.com",
    info: {
      status: "Inactive",
      role: "HR",
      yearsOfExperience: 6,
      department: "HR",
      location: "Seattle",
    },
  },
  {
    id: 7,
    name: "Ethan Ford",
    email: "ethan@example.com",
    info: {
      status: "Pending",
      role: "Support",
      yearsOfExperience: 1,
      department: "Support",
      location: "Denver",
    },
  },
  {
    id: 8,
    name: "Fiona Green",
    email: "fiona@example.com",
    info: {
      status: "Active",
      role: "Developer",
      yearsOfExperience: 5,
      department: "Engineering",
      location: "Miami",
    },
  },
  {
    id: 9,
    name: "George Harris",
    email: "george@example.com",
    info: {
      status: "Inactive",
      role: "Manager",
      yearsOfExperience: 8,
      department: "Management",
      location: "Los Angeles",
    },
  },
  {
    id: 10,
    name: "Hannah Irving",
    email: "hannah@example.com",
    info: {
      status: "Active",
      role: "Designer",
      yearsOfExperience: 3,
      department: "Design",
      location: "New York",
    },
  },
  {
    id: 11,
    name: "Ian Jackson",
    email: "ian@example.com",
    info: {
      status: "Pending",
      role: "Support",
      yearsOfExperience: 2,
      department: "Support",
      location: "Boston",
    },
  },
  {
    id: 12,
    name: "Julia King",
    email: "julia@example.com",
    info: {
      status: "Active",
      role: "Admin",
      yearsOfExperience: 6,
      department: "Management",
      location: "San Francisco",
    },
  },
  {
    id: 13,
    name: "Kevin Lee",
    email: "kevin@example.com",
    info: {
      status: "Inactive",
      role: "Developer",
      yearsOfExperience: 4,
      department: "Engineering",
      location: "Austin",
    },
  },
  {
    id: 14,
    name: "Laura Martin",
    email: "laura@example.com",
    info: {
      status: "Pending",
      role: "HR",
      yearsOfExperience: 5,
      department: "HR",
      location: "Chicago",
    },
  },
  {
    id: 15,
    name: "Michael Nelson",
    email: "michael@example.com",
    info: {
      status: "Active",
      role: "Developer",
      yearsOfExperience: 7,
      department: "Engineering",
      location: "New York",
    },
  },
  {
    id: 16,
    name: "Nina Owens",
    email: "nina@example.com",
    info: {
      status: "Inactive",
      role: "Designer",
      yearsOfExperience: 2,
      department: "Design",
      location: "Seattle",
    },
  },
  {
    id: 17,
    name: "Oliver Parker",
    email: "oliver@example.com",
    info: {
      status: "Pending",
      role: "Support",
      yearsOfExperience: 3,
      department: "Support",
      location: "Denver",
    },
  },
  {
    id: 18,
    name: "Paula Quinn",
    email: "paula@example.com",
    info: {
      status: "Active",
      role: "Manager",
      yearsOfExperience: 6,
      department: "Management",
      location: "San Francisco",
    },
  },
  {
    id: 19,
    name: "Quentin Ross",
    email: "quentin@example.com",
    info: {
      status: "Inactive",
      role: "Developer",
      yearsOfExperience: 4,
      department: "Engineering",
      location: "Austin",
    },
  },
  {
    id: 20,
    name: "Rachel Scott",
    email: "rachel@example.com",
    info: {
      status: "Active",
      role: "Designer",
      yearsOfExperience: 5,
      department: "Design",
      location: "Boston",
    },
  },
  {
    id: 21,
    name: "Steven Turner",
    email: "steven@example.com",
    info: {
      status: "Pending",
      role: "Support",
      yearsOfExperience: 1,
      department: "Support",
      location: "Miami",
    },
  },
  {
    id: 22,
    name: "Tina Underwood",
    email: "tina@example.com",
    info: {
      status: "Active",
      role: "Manager",
      yearsOfExperience: 8,
      department: "Management",
      location: "Los Angeles",
    },
  },
  {
    id: 23,
    name: "Victor Vaughn",
    email: "victor@example.com",
    info: {
      status: "Inactive",
      role: "Developer",
      yearsOfExperience: 3,
      department: "Engineering",
      location: "New York",
    },
  },
  {
    id: 24,
    name: "Wendy White",
    email: "wendy@example.com",
    info: {
      status: "Active",
      role: "Designer",
      yearsOfExperience: 4,
      department: "Design",
      location: "San Francisco",
    },
  },
];
